---
layout: post
title: "seoul2016"
author: "Young Ho Lee"
date: "2017.10.02"
output: html_document
categories: Contest
---

```{r setup, include=FALSE}
# Basic Packages
library(dplyr)
library(ggplot2)
library(readr)
library(stringr)
library(gridExtra)
library(openxlsx)

#setwd
knitr::opts_chunk$set(root.dir = "D:/Data/Public_data/real_transaction_price_2017/2016/")
```

# 1. Data Import
```{r}
seoul2016 <- read.xlsx("D:/Data/Public_data/real_transaction_price_2017/2016/seoul2016.xlsx")

split_gu <- function(x){
  strsplit(x, split = ',')[[1]][2]
}

split_dong <- function(x){
  strsplit(x, split = ',')[[1]][3]
}

seoul2016$êµ? <- sapply(seoul2016$?‹œêµ°êµ¬, split_gu)
seoul2016$?™ <- sapply(seoul2016$?‹œêµ°êµ¬, split_dong)

seoul2016$ê³„ì•½?¼ <- as.factor(seoul2016$ê³„ì•½?¼)
seoul2016$ê±´ë¬¼ì¢…ë¥˜ <- as.factor(seoul2016$ê±´ë¬¼ì¢…ë¥˜)
seoul2016$êµ? <- as.factor(seoul2016$êµ?)
seoul2016$?™ <- as.factor(seoul2016$?™)

seoul2016 <- seoul2016 %>%
  select(-?‹œêµ°êµ¬)

str(seoul2016)
summary(seoul2016)
```

# 2. Data Exploration
## 1) Visualization
### 1-1) ? „?š©ë©´ì 
```{r}
seoul2016 %>%  
  ggplot(aes(x = seoul2016$`? „?š©ë©´ì (?¡)`, y = log(seoul2016$`?›”?„¸(ë§Œì›)`), 
             color = seoul2016$`? „?š©ë©´ì (?¡)`)) +
  geom_point(shape = 21) + geom_line() +
  xlab("? „?š©ë©´ì (?¡)") + ylab("log(?›”?„¸(ë§Œì›))") + 
  scale_color_gradient(low = "deepskyblue", high = "hotpink",
                       name = "? „?š©ë©´ì (?¡)") +
  theme(axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16))
```

### 1-2) ê³„ì•½?…„?›”
```{r}
seoul2016 %>%
  ggplot(aes(x = factor(seoul2016$ê³„ì•½?…„?›”), y = log(seoul2016$`?›”?„¸(ë§Œì›)`), 
             fill = factor(seoul2016$ê³„ì•½?…„?›”))) +
  geom_jitter(color = 'grey', alpha = .2) +
  geom_violin(alpha = .7) + xlab("ê³„ì•½?…„?›”") + ylab("log(?›”?„¸(ë§Œì›))") +
  scale_fill_discrete(name = "ê³„ì•½?…„?›”") +
  theme(axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16))
```

### 1-3) ê³„ì•½?¼
```{r}
seoul2016 %>%
  ggplot(aes(x = seoul2016$ê³„ì•½?¼, y = log(seoul2016$`?›”?„¸(ë§Œì›)`), 
             fill = seoul2016$ê³„ì•½?¼)) +
  geom_jitter(color = 'grey', alpha = .2) +
  geom_violin(alpha = .7) + xlab("ê³„ì•½?¼") + ylab("log(?›”?„¸(ë§Œì›))") +
  scale_fill_discrete(name = "ê³„ì•½?¼") +
  theme(axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16))
```

### 1-4) ë³´ì¦ê¸?(ë§Œì›)
```{r}
seoul2016 %>%  
  ggplot(aes(x = log(seoul2016$`ë³´ì¦ê¸?(ë§Œì›)`), y = log(seoul2016$`?›”?„¸(ë§Œì›)`), 
             color = log(seoul2016$`ë³´ì¦ê¸?(ë§Œì›)`))) +
  geom_point(shape = 21) + geom_line() +
  xlab("ë³´ì¦ê¸?(ë§Œì›)") + ylab("log(?›”?„¸(ë§Œì›))") +
  scale_color_gradient(low = "deepskyblue", high = "hotpink",
                       name = "ë³´ì¦ê¸?(ë§Œì›)") +
  theme(axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16))
```

### 1-5) ì¸?
```{r}
seoul2016 %>%  
  ggplot(aes(x = factor(seoul2016$ì¸?), y = log(seoul2016$`?›”?„¸(ë§Œì›)`), 
             fill = factor(seoul2016$ì¸?))) +
  geom_boxplot() +
  xlab("ì¸?") + ylab("log(?›”?„¸(ë§Œì›))") +
  scale_fill_discrete(name = "ì¸?") + theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  theme(axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16))
```

### 1-6) ê±´ì¶•?…„?„
```{r}
seoul2016 %>%
  mutate(built_year = cut(seoul2016$ê±´ì¶•?…„?„, seq(1960, 2020, by = 10),
                            labels = paste0(seq(1960, 2010, by = 10), "s"))) %>%
  ggplot(aes(x = factor(built_year), y = log(seoul2016$`?›”?„¸(ë§Œì›)`),
             fill = factor(built_year))) +
  geom_jitter(color = 'grey', alpha = .2) +
  geom_violin(alpha = .7) + xlab("ê±´ì¶•?…„?„") + ylab("log(?›”?„¸(ë§Œì›))") +
  scale_fill_discrete(name = "ê±´ì¶•?…„?„")  +
  theme(axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16))
```

### 1-7) ê±´ë¬¼ì¢…ë¥˜
```{r}
seoul2016 %>%
  ggplot(aes(x = seoul2016$ê±´ë¬¼ì¢…ë¥˜, y = log(seoul2016$`?›”?„¸(ë§Œì›)`), 
             fill = seoul2016$ê±´ë¬¼ì¢…ë¥˜)) +
  geom_jitter(color = 'grey', alpha = .2) +
  geom_violin(alpha = .7) + xlab("ê±´ë¬¼ì¢…ë¥˜") + ylab("log(?›”?„¸(ë§Œì›))") +
  scale_fill_discrete(name = "ê±´ë¬¼ì¢…ë¥˜") +
  theme(axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16))
```

### 1-8) êµ?
```{r}
seoul2016 %>%
  ggplot(aes(x = seoul2016$êµ?, y = log(seoul2016$`?›”?„¸(ë§Œì›)`), 
             fill = seoul2016$êµ?)) +
  geom_jitter(color = 'grey', alpha = .2) +
  geom_violin(alpha = .7) + xlab("?ì¹˜êµ¬") + ylab("log(?›”?„¸(ë§Œì›))") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  theme(axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16)) + 
  theme(legend.position = "none")
```

### 1-9) log(?›”?„¸(ë§Œì›))
```{r}
library(ggmap)

Seoul <- get_map(location = 'seoul',
                 zoom = 11,
                 maptype = "roadmap")

seoul2016.arrange <- seoul2016 %>%
  arrange(`?›”?„¸(ë§Œì›)`)

ggmap(Seoul) + 
    geom_point(data = seoul2016.arrange, aes(x = x, y = y, 
                                             color = log(`?›”?„¸(ë§Œì›)`)), 
               alpha = .075) + 
    scale_color_gradient(low = "green", high = "red")
```


# 3. Modeling
```{r}
seoul2016$`?›”?„¸(ë§Œì›)` <- ifelse(seoul2016$`?›”?„¸(ë§Œì›)` == 0, 1, seoul2016$`?›”?„¸(ë§Œì›)`)

set.seed(1234)
trainIndex <- sample(x = 1:nrow(seoul2016), size = 0.7 * nrow(seoul2016))
train <- seoul2016[trainIndex, ]
test <- seoul2016[-trainIndex, ]
```

## 1) Raw Model
```{r}
monthlyRent_model <- lm(`?›”?„¸(ë§Œì›)` ~ ., data = train[, -12])
summary(monthlyRent_model)
```

## 2) Log model
```{r}
log_model <- lm(log(`?›”?„¸(ë§Œì›)`) ~ ., data = train[, -12])
summary(log_model)
```


# 4. Model Evaluation
## 1) Raw model
```{r}
rmse <- function(actual, predict){
  if(length(actual) != length(predict))
      stop("The length of two vectors are different")

  length <- length(actual)
  errorSum <- sum((actual - predict)^2)
  
  return(sqrt(errorSum / length))
}
```

```{r}
predict_price <- predict(monthlyRent_model, test)
plot(predict_price)

rmse(test$`?›”?„¸(ë§Œì›)`, predict_price)
```

## 2) Log model
```{r}
rmsle <- function(pred, act) {
    if(length(pred) != length(act))
        stop("The length of two vectors are different")
    
    len <- length(pred)
    pred <- log(pred + 1)
    act <- log(act + 1)
    
    msle <- mean((pred - act)^2)
    
    return(sqrt(msle))
}
```

```{r}
log_pred <- predict(log_model, test)
log_pred <- exp(log_pred)
plot(log_pred)

rmsle(log_pred, test$`?›”?„¸(ë§Œì›)`)
```

```{r}
write.csv(seoul2016, "seoul2016.csv", row.names = FALSE)
```

# 5. Model Improvement
## 1) Data Import
```{r}
final <- read.xlsx("D:/Data/Public_data/real_transaction_price_2017/2016/seoul2016_final.xlsx")

str(final)
summary(final)

final <- final %>%
  mutate(ê°•ë‚¨êµ? = ifelse(final$êµ? == "ê°•ë‚¨êµ?", 1, 0),
         ê°•ë™êµ? = ifelse(final$êµ? == "ê°•ë™êµ?", 1, 0),
         ê°•ë¶êµ? = ifelse(final$êµ? == "ê°•ë¶êµ?", 1, 0),
         ê°•ì„œêµ? = ifelse(final$êµ? == "ê°•ì„œêµ?", 1, 0),
         ê´€?•…êµ? = ifelse(final$êµ? == "ê´€?•…êµ?", 1, 0),
         ê´‘ì§„êµ? = ifelse(final$êµ? == "ê´‘ì§„êµ?", 1, 0),
         êµ¬ë¡œêµ? = ifelse(final$êµ? == "êµ¬ë¡œêµ?", 1, 0),
         ê¸ˆì²œêµ? = ifelse(final$êµ? == "ê¸ˆì²œêµ?", 1, 0),
         ?…¸?›êµ? = ifelse(final$êµ? == "?…¸?›êµ?", 1, 0),
         ?„ë´‰êµ¬ = ifelse(final$êµ? == "?„ë´‰êµ¬", 1, 0),
         ?™??€ë¬¸êµ¬ = ifelse(final$êµ? == "?™??€ë¬¸êµ¬", 1, 0),
         ?™?‘êµ? = ifelse(final$êµ? == "?™?‘êµ?", 1, 0),
         ë§ˆí¬êµ? = ifelse(final$êµ? == "ë§ˆí¬êµ?", 1, 0),
         ?„œ??€ë¬¸êµ¬ = ifelse(final$êµ? == "?„œ??€ë¬¸êµ¬", 1, 0),
         ?„œì´ˆêµ¬ = ifelse(final$êµ? == "?„œì´ˆêµ¬", 1, 0),
         ?„±?™êµ? = ifelse(final$êµ? == "?„±?™êµ?", 1, 0),
         ?„±ë¶êµ¬ = ifelse(final$êµ? == "?„±ë¶êµ¬", 1, 0),
         ?†¡?ŒŒêµ? = ifelse(final$êµ? == "?†¡?ŒŒêµ?", 1, 0),
         ?–‘ì²œêµ¬ = ifelse(final$êµ? == "?–‘ì²œêµ¬", 1, 0),
         ?˜?“±?¬êµ? = ifelse(final$êµ? == "?˜?“±?¬êµ?", 1, 0),
         ?š©?‚°êµ? = ifelse(final$êµ? == "?š©?‚°êµ?", 1, 0),
         ??€?‰êµ? = ifelse(final$êµ? == "??€?‰êµ?", 1, 0),
         ì¢…ë¡œêµ? = ifelse(final$êµ? == "ì¢…ë¡œêµ?", 1, 0),
         ì¤‘êµ¬ = ifelse(final$êµ? == "ì¤‘êµ¬", 1, 0),
         ì¤‘ë‘êµ? = ifelse(final$êµ? == "ì¤‘ë‘êµ?", 1, 0),
         ?•„?ŒŒ?Š¸ = ifelse(final$ê±´ë¬¼ì¢…ë¥˜ == "?•„?ŒŒ?Š¸", 1, 0),
         "?—°ë¦?/?‹¤?„¸??€" = ifelse(final$ê±´ë¬¼ì¢…ë¥˜ == "?—°ë¦?/?‹¤?„¸??€", 1, 0),
         ?˜¤?”¼?Š¤?…” = ifelse(final$ê±´ë¬¼ì¢…ë¥˜ == "?˜¤?”¼?Š¤?…”", 1, 0),
         ì´? = ifelse(final$ê³„ì•½?¼ == "1~10", 1, 0),
         ì¤? = ifelse(final$ê³„ì•½?¼ == "11~20", 1, 0),
         ë§? = ifelse(final$ê³„ì•½?¼ == "21~31", 1, 0)) %>%
  select(-c(êµ?, ê±´ë¬¼ì¢…ë¥˜, ê³„ì•½?¼))

# Data split
raw <- final[, c(2:9, 21:51)]
final <- final[, c(2:9, 16:51)]
```

## 2) Raw model
```{r}
raw$`?›”?„¸(ë§Œì›)` <- ifelse(raw$`?›”?„¸(ë§Œì›)` == 0, 1, raw$`?›”?„¸(ë§Œì›)`)

set.seed(1234)
trainIndex <- sample(x = 1:nrow(raw), size = 0.7 * nrow(raw))
tr.raw <- raw[trainIndex, ]
te.raw <- raw[-trainIndex, ]
```

```{r}
raw.model <- lm(log(`?›”?„¸(ë§Œì›)`) ~ ., data = tr.raw)
summary(raw.model)
```

```{r}
rmsle <- function(pred, act) {
    if(length(pred) != length(act))
        stop("The length of two vectors are different")
    
    len <- length(pred)
    pred <- log(pred + 1)
    act <- log(act + 1)
    
    msle <- mean((pred - act)^2)
    
    return(sqrt(msle))
}
```

```{r}
raw.pred <- predict(raw.model, te.raw)
raw.pred <- exp(raw.pred)
plot(raw.pred)

rmsle(raw.pred, te.raw$`?›”?„¸(ë§Œì›)`)
```

## 3) Visualization
```{r}
final <- final %>%
  dplyr::mutate(theater_c = ifelse(theater_dist < 300, 5, 
                            ifelse(theater_dist > 300 & theater_dist < 600, 4,
                            ifelse(theater_dist > 600 & theater_dist < 900, 3, 
                            ifelse(theater_dist > 900 & theater_dist < 1200, 2,
                            ifelse(theater_dist > 1200, 1, NA)))))) %>%
  dplyr::mutate(subway_c = ifelse(subway_dist < 300, 5, 
                           ifelse(subway_dist > 300 & subway_dist < 600, 4,
                           ifelse(subway_dist > 600 & subway_dist < 900, 3, 
                           ifelse(subway_dist > 900 & subway_dist < 1200, 2,
                           ifelse(subway_dist > 1200, 1, NA)))))) %>%
  dplyr::mutate(univ_c = ifelse(univ_dist < 300, 5, 
                         ifelse(univ_dist > 300 & univ_dist < 600, 4,
                         ifelse(univ_dist > 600 & univ_dist < 900, 3, 
                         ifelse(univ_dist > 900 & univ_dist < 1200, 2,
                         ifelse(univ_dist > 1200, 1, NA)))))) %>%
  dplyr::mutate(host_c = ifelse(host_dist < 300, 5, 
                         ifelse(host_dist > 300 & host_dist < 600, 4,
                         ifelse(host_dist > 600 & host_dist < 900, 3, 
                         ifelse(host_dist > 900 & host_dist < 1200, 2,
                         ifelse(host_dist > 1200, 1, NA)))))) %>%
  dplyr::mutate(police_c = ifelse(police_dist < 300, 5, 
                           ifelse(police_dist > 300 & police_dist < 600, 4,
                           ifelse(police_dist > 600 & police_dist < 900, 3, 
                           ifelse(police_dist > 900 & police_dist < 1200, 2,
                           ifelse(police_dist > 1200, 1, NA)))))) %>%
  select(-c(theater_dist, subway_dist, univ_dist, host_dist, police_dist))
```

### 3-1) Theater
```{r}
final %>%
  ggplot(aes(x = factor(theater_c), y = log(`?›”?„¸(ë§Œì›)`), 
             color = factor(theater_c))) +
  geom_point(position = "jitter", alpha = 0.1) +
  xlab("ê·¹ì¥ê³¼ì˜ ê±°ë¦¬(ê°€ì¤‘ì¹˜)") + scale_color_discrete(name = "ê°€ì¤‘ì¹˜") +
  theme(axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16))
```

### 3-2) Subway
```{r}
final %>%
  ggplot(aes(x = factor(subway_c), y = log(`?›”?„¸(ë§Œì›)`), 
             color = factor(subway_c))) +
  geom_point(position = "jitter", alpha = 0.1) +
  xlab("ì§€?•˜ì² ì—­ê³¼ì˜ ê±°ë¦¬(ê°€ì¤‘ì¹˜)") + scale_color_discrete(name = "ê°€ì¤‘ì¹˜") +
  theme(axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16))
```

### 3-3) University
```{r}
final %>%
  ggplot(aes(x = factor(univ_c), y = log(`?›”?„¸(ë§Œì›)`), 
             color = factor(univ_c))) +
  geom_point(position = "jitter", alpha = 0.1) +
  xlab("??€?•™êµì?€?˜ ê±°ë¦¬(ê°€ì¤‘ì¹˜)") + scale_color_discrete(name = "ê°€ì¤‘ì¹˜") +
  theme(axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16))
```

### 3-4) Hospital
```{r}
final %>%
  ggplot(aes(x = factor(host_c), y = log(`?›”?„¸(ë§Œì›)`), 
             color = factor(host_c))) +
  geom_point(position = "jitter", alpha = 0.1) +
  xlab("ì¢…í•©ë³‘ì›ê³¼ì˜ ê±°ë¦¬(ê°€ì¤‘ì¹˜)") + scale_color_discrete(name = "ê°€ì¤‘ì¹˜") +
  theme(axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16))
```

### 3-5) Police Office
```{r}
final %>%
  ggplot(aes(x = factor(police_c), y = log(`?›”?„¸(ë§Œì›)`), 
             color = factor(police_c))) +
  geom_point(position = "jitter", alpha = 0.1) +
  xlab("ê²½ì°°?„œ??€?˜ ê±°ë¦¬(ê°€ì¤‘ì¹˜)") + scale_color_discrete(name = "ê°€ì¤‘ì¹˜") +
  theme(axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16))
```

## 4) Final model
```{r}
final$`?›”?„¸(ë§Œì›)` <- ifelse(final$`?›”?„¸(ë§Œì›)` == 0, 1, final$`?›”?„¸(ë§Œì›)`)

tr.final <- final[trainIndex, ]
te.final <- final[-trainIndex, ]
```

```{r}
final.model <- lm(log(`?›”?„¸(ë§Œì›)`) ~ ., data = tr.final[, -16])
summary(final.model)
```

```{r}
final.pred <- predict(final.model, te.final)
final.pred <- exp(final.pred)
plot(final.pred)

rmsle(final.pred, te.final$`?›”?„¸(ë§Œì›)`)
```

```{r}
# log x : 67.59016
# raw(log o) : 0.4986276
# + Theater : 0.4974584
# + Theater, subway : 0.4938038
# + Theater, subway, university : 0.4935597
# + Theater, subway, university, hospital : 0.4915776
# + Theater, subway, university, hospital, police office : 0.4907772

# dist
# + Theater : 0.4950176
# + Theater, subway : 0.4893252
# + Theater, subway, university : 0.4893243
# + Theater, subway, university, hospital : 0.486896
# + Theater, subway, university, hospital, police office : 0.4868355

# distance category
# + Theater : 0.4972346
# + Theater, subway : 0.4911091
# + Theater, subway, university : 0.49091
# + Theater, subway, university, hospital : 0.4886029
# + Theater, subway, university, hospital, police office : 0.4880586
```

