---
layout: post
title: "ggvis"
author: "Young Ho Lee"
date: "2018.04.06"
categories: ggvis
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Basic packages
library(ggvis)
library(dplyr)

# Define image sizes
img.width <- 450
img.height <- 300
```

# 1. Introduction
```{r}
mtcars %>%
  ggvis(x = ~wt, y = ~mpg) %>%
  layer_points() %>%
  set_options(width = img.width, height = img.height)
```

```{r}
mtcars %>%
  ggvis(x = ~mpg, y = ~disp) %>%
  mutate(disp = disp / 61.0237) %>% # convert engine displacement to litres
  layer_points()
```

```{r}
mtcars %>%
  ggvis(~mpg, ~disp, stroke = ~vs) %>%
  layer_points()
```

```{r}
mtcars %>%
  ggvis(~mpg, ~disp, fill = ~vs) %>%
  layer_points()
```

```{r}
mtcars %>%
  ggvis(~mpg, ~disp, size = ~vs) %>%
  layer_points()
```

```{r}
mtcars %>%
  ggvis(~mpg, ~disp, shape = ~factor(cyl)) %>%
  layer_points()
```

```{r}
# If you want to make the points a fixed colour or size, you need to use :=
mtcars %>% 
  ggvis(~mpg, ~disp, fill := "red", stroke := "black") %>%
  layer_points()
```

```{r}
mtcars %>%
  ggvis(~wt, ~mpg, size := 300, opacity := 0.4) %>%
  layer_points()
```

# 2. Interaction
```{r}
mtcars %>%
  ggvis(~wt, ~mpg,
        size := input_slider(10, 100),
        opacity := input_slider(0, 1)) %>%
  layer_points()
```

```{r}
mtcars %>%
  ggvis(~wt) %>%
  layer_histograms(width = input_slider(0, 2, step = 0.10, label = "width"),
                   center = input_slider(0, 2, step = 0.05, label = "center")c)
```

```{r}
# Press the left and right arrows to control the size of the points in the next example.
keys_s <- left_right(10, 1000, step = 50) # up_down()
mtcars %>%
  ggvis(~wt, ~mpg, size := keys_s, opacity := 0.5) %>%
  layer_points()
```

```{r}
mtcars %>% ggvis(~wt, ~mpg) %>% 
  layer_points() %>% 
  add_tooltip(function(df) df$wt)
```

# 3. Layers
## (1) Simple layers
```{r}
df <- data.frame(x = 1:10, y = runif(10))
df %>%
  ggvis(~x, ~y) %>%
  layer_paths()
```

```{r}
t <- seq(0, 2 * pi, length.out = 100)
df <- data.frame(x = sin(t), y = cos(t))
df %>%
  ggvis(~x, ~y) %>%
  layer_paths(fill := "red")
```

```{r}
df <- data.frame(x = 1:10, y = runif(10))
df %>%
  ggvis(~x, ~y) %>%
  layer_ribbons()
```

```{r}
df <- data.frame(x = 1:10, y = runif(10))
df %>%
  ggvis(~x, ~y + 0.1, y2 = ~y - 0.1) %>%
  layer_ribbons()
```

```{r}
set.seed(1014)
df <- data.frame(x1 = runif(5), x2 = runif(5), y1 = runif(5), y2 = runif(5))
df %>%
  ggvis(~x1, ~y1, x2 = ~x2, y2 = ~y2, fillOpacity := 0.1) %>%
  layer_rects()
```

```{r}
df <- data.frame(x = 3:1, y = c(1, 3, 2), label = c("a", "b", "c"))
df %>% 
  ggvis(~x, ~y, text := ~label) %>% 
  layer_text(fontSize := 20, angle := 45)
```

